import React from 'react'
import { motion } from "framer-motion"
import logo from "./../../assets/Finance_logo.png"

const Goals = (image) => {
  return (
        <div className='flex items-center flex-col justify-around w-[full] '>
            <h1 className=' font-semibold text-[#EBA91F] sm:text-[50px] text-[30px] p-[80px] '>
            Investment Plans of the Company
            </h1>
            {/* <h1 className=' font-semibold text-[#EBA91F] sm:text-[50px] text-[30px] '>
                GOALS
            </h1>
            <div className='flex flex-col justify-around h-[190vh]'>

            <motion.div

            initial={{ opacity: 0, x: -60 }}
            animate={{x: 0,}}
            whileInView={{ opacity: 1 }}
            transition={{ ease: "easeOut", duration: 1.2}}
            className='flex justify-center min-h-[200px]'
            >
                <div className='flex flex-col justify-around text-center sm:text-left items-center sm:flex-row sm:justify-between sm:w-[430px]'>
                    <img className='w-[50px] h-[55px] sm:w-[100px] sm:h-[110px] ' src={logo}/>
                    <p className='max-w-[300px]'>
                    Lorem ipsum dolor aute dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                    </p>
                </div>
            </motion.div>


            <motion.div

            initial={{ opacity: 0, x: -60 }}
            animate={{x: 0,}}
            whileInView={{ opacity: 1 }}
            transition={{ ease: "easeOut", duration: 1.2}}
            className='flex justify-center min-h-[200px]'
            >
                <div className='flex flex-col justify-around text-center sm:text-right items-center sm:flex-row-reverse sm:justify-between sm:w-[430px]'>
                    <img className='w-[50px] h-[55px] sm:w-[100px] sm:h-[110px] ' src={logo}/>
                    <p className='max-w-[300px]'>
                    Lorem ipsum dolor aute dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                    </p>
                </div>
            </motion.div>


            <motion.div

            initial={{ opacity: 0, x: -60 }}
            animate={{x: 0,}}
            whileInView={{ opacity: 1 }}
            transition={{ ease: "easeOut", duration: 1.2}}
            className='flex justify-center min-h-[200px]'
            >
                <div className='flex flex-col justify-around text-center sm:text-left items-center sm:flex-row sm:justify-between sm:w-[430px]'>
                    <img className='w-[50px] h-[55px] sm:w-[100px] sm:h-[110px] ' src={logo}/>
                    <p className='max-w-[300px]'>
                    Lorem ipsum dolor aute dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                    </p>
                </div>
            </motion.div>
                            
            </div> */}
        <div className='flex items-center flex-wrap justify-around '>


        <div className='flex flex-wrap justify-around items-center min-w-[20px] p-[15px] md:max-w-[400px] max-w-[495px]  flex-col'>
                <div className='flex justify-center h-[120px] w-[120px] pb-[30px]' id='image'>
                    <img src={logo}/>
                </div>
                <div className=' lg:w-[90%]' id='text'>
                    <h2 className='text-[20px] text-gray-800 font-semibold'>
                    Introduction to Tokenization
                    </h2>
                    <p>
                    Our company plans to introduce tokens that represent company shares. Each individual purchasing these tokens becomes a participant in the profits generated by the company. 50% of all company shares will be reflected through tokens, and their market quantity will be adjusted as needed.                    </p>
                </div>
            </div>
            <div className='flex justify-around items-center min-w-[20px] p-[15px] md:max-w-[400px] max-w-[495px]  flex-col'>
                <div className='flex justify-center h-[120px] w-[120px] pb-[30px]' id='image'>
                    <img src={logo}/>
                </div>
                <div className=' lg:w-[90%]' id='text'>
                    <h2 className='text-[20px] text-gray-800 font-semibold'>
                    Technological Infrastructure
                    </h2>
                    <p>
                    In the initial phase, we will launch a website with a wallet, and our tokens will be listed on platforms such as CoinMarketCap and CoinGecko. Additionally, we will create our own wallet on our website, enabling storage, value tracking, and profit generation from held tokens.                    </p>
                </div>
            </div>
            <div className='flex justify-around items-center min-w-[20px] p-[15px] md:max-w-[400px] max-w-[495px]  flex-col'>
                <div className='flex justify-center h-[120px] w-[120px] pb-[30px]' id='image'>
                    <img src={logo}/>
                </div>
                <div className=' lg:w-[90%]' id='text'>
                    <h2 className='text-[20px] text-gray-800 font-semibold'>
                    Development Funding
                    </h2>
                    <p>
                    All proceeds from token sales will be allocated to platform development and the purchase of assets on which subsequent projects will be based. Our tokens differ from standard stablecoins, as their value will increase with the associated asset, making investments more attractive.                    </p>
                </div>
            </div>
            <div className='flex justify-around items-center min-w-[20px] p-[15px] md:max-w-[400px] max-w-[495px]  flex-col'>
                <div className='flex justify-center h-[120px] w-[120px] pb-[30px]' id='image'>
                    <img src={logo}/>
                </div>
                <div className=' lg:w-[90%]' id='text'>
                    <h2 className='text-[20px] text-gray-800 font-semibold'>
                    Investments In Assets
                    </h2>
                    <p>
                    Managing the acquired funds, the company plans to invest in diverse income-generating assets. Assets will be available for purchase through tokenization, allowing investors to participate in real estate, lands, hotels, and other projects.                    </p>
                </div>
            </div>
            <div className='flex justify-around items-center min-w-[20px] p-[15px] md:max-w-[400px] max-w-[495px]  flex-col'>
                <div className='flex justify-center h-[120px] w-[120px] pb-[30px]' id='image'>
                    <img src={logo}/>
                </div>
                <div className=' lg:w-[90%]' id='text'>
                    <h2 className='text-[20px] text-gray-800 font-semibold'>
                    Asset Tokenization
                    </h2>
                    <p>
                    Our platform will enable the tokenization of assets, allowing users to acquire shares in various investments. Tokens, such as "Real Golds," will be used to pay commissions from the profits earned by the company and will be available on our platform.                    </p>
                </div>
            </div>
            <div className='flex justify-around items-center min-w-[20px] p-[15px] md:max-w-[400px] max-w-[495px]  flex-col'>
                <div className='flex justify-center h-[120px] w-[120px] pb-[30px]' id='image'>
                    <img src={logo}/>
                </div>
                <div className=' lg:w-[90%]' id='text'>
                    <h2 className='text-[20px] text-gray-800 font-semibold'>
                    Community Decisions And Investment
                    </h2>
                    <p>
                    We are building a community that can propose asset tokenization and vote on decisions related to a particular asset (sale, rental, etc.). Our company will manage tokenization, the sale of tokens associated with a specific asset, and profits will be evenly distributed among token holders.
                    </p>
                </div>
            </div>
            <div className='flex justify-around items-center min-w-[20px] p-[15px] md:max-w-[400px] max-w-[495px]  flex-col'>
                <div className='flex justify-center h-[120px] w-[120px] pb-[30px]' id='image'>
                    <img src={logo}/>
                </div>
                <div className=' lg:w-[90%]' id='text'>
                    <h2 className='text-[20px] text-gray-800 font-semibold'>
                    International Expansion
                    </h2>
                    <p>
                    Over time, we plan to expand into international markets by establishing branches in different countries.              
                    </p>
                </div>
            </div>
        </div>
            {/* <div className='h-[80px] bg-blue-500 w-[200px]'>
                h
            </div>
            <div className='h-[80px] bg-purple-500 w-[200px]'>
                h
            </div>
            <div className='h-[80px] bg-green-500 w-[200px]'>
                h

            </div> */}
            </div>

  )
}

export default Goals